#!/usr/bin/env bash
# Drift Coach — one-shot installer for Linux / macOS / WSL
# - Checks Node 20+
# - Installs deps (uses npm if pnpm/bun aren't found)
# - Builds the production bundle
# - Picks a free port for HTTP (default 3002, fallback to next available)
# - Picks a free UDP port for Forza (default 5330, fallback)
# - Writes .env with chosen ports
# - Prints how to start

set -e

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

cyan()   { printf '\033[36m%s\033[0m\n' "$*"; }
green()  { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
red()    { printf '\033[31m%s\033[0m\n' "$*"; }

cyan "[1/5] Checking Node.js >= 20"
if ! command -v node >/dev/null 2>&1; then
  red "Node.js is not installed."
  yellow "Install Node 20+ from https://nodejs.org/ and re-run this script."
  exit 1
fi
NODE_MAJOR=$(node -p "process.versions.node.split('.')[0]")
if [ "$NODE_MAJOR" -lt 20 ]; then
  red "Node $(node -v) is too old — need 20+."
  yellow "Upgrade Node and re-run."
  exit 1
fi
green "  Node $(node -v) OK"

cyan "[2/5] Picking an open HTTP port"
# Try the user's preferred port (or 3002) first; if taken, walk forward
DESIRED_PORT="${PORT:-3002}"
port_in_use() {
  # Cross-platform check: works on linux (ss/lsof), macOS, WSL
  if command -v ss >/dev/null 2>&1;   then ss -ltn 2>/dev/null | awk '{print $4}' | grep -qE ":$1\$"; return $?; fi
  if command -v lsof >/dev/null 2>&1; then lsof -iTCP:"$1" -sTCP:LISTEN -P -n >/dev/null 2>&1; return $?; fi
  if command -v netstat >/dev/null 2>&1; then netstat -an 2>/dev/null | grep -qE "[:.]$1 .*LISTEN"; return $?; fi
  return 1
}
HTTP_PORT="$DESIRED_PORT"
for _ in 1 2 3 4 5 6 7 8 9 10; do
  if port_in_use "$HTTP_PORT"; then
    HTTP_PORT=$((HTTP_PORT + 1))
  else
    break
  fi
done
if [ "$HTTP_PORT" != "$DESIRED_PORT" ]; then
  yellow "  Port $DESIRED_PORT was in use — using $HTTP_PORT instead"
fi
green "  HTTP port: $HTTP_PORT"

cyan "[3/5] Picking an open UDP port for Forza Data Out"
DESIRED_UDP="${FORZA_PORT:-5330}"
udp_in_use() {
  if command -v ss >/dev/null 2>&1;   then ss -lun 2>/dev/null | awk '{print $4}' | grep -qE ":$1\$"; return $?; fi
  if command -v lsof >/dev/null 2>&1; then lsof -iUDP:"$1" -P -n >/dev/null 2>&1; return $?; fi
  return 1
}
UDP_PORT="$DESIRED_UDP"
for _ in 1 2 3 4 5; do
  if udp_in_use "$UDP_PORT"; then
    UDP_PORT=$((UDP_PORT + 1))
  else
    break
  fi
done
if [ "$UDP_PORT" != "$DESIRED_UDP" ]; then
  yellow "  UDP $DESIRED_UDP was in use — using $UDP_PORT instead"
fi
green "  Forza UDP port: $UDP_PORT (set this in Forza Data Out > Out Port)"

cyan "[4/5] Installing dependencies"
if [ -d node_modules ] && [ -f package-lock.json ]; then
  green "  node_modules already present; skipping (delete it to force a fresh install)"
else
  if command -v pnpm >/dev/null 2>&1; then
    pnpm install
  elif command -v bun >/dev/null 2>&1; then
    bun install
  else
    npm install
  fi
fi

cyan "[5/5] Building production bundle"
npm run build

# Write a starter .env if one doesn't exist yet so subsequent starts use the same ports.
if [ ! -f .env ]; then
  cat > .env <<EOF
# Auto-generated by install.sh. Override anything here.
PORT=$HTTP_PORT
HOST=0.0.0.0
FORZA_PORT=$UDP_PORT

# AI provider keys are managed in-app at http://localhost:$HTTP_PORT/settings
# Set them there OR uncomment the env vars below.
# OLLAMA_API_KEY=
# ANTHROPIC_API_KEY=
# OPENAI_API_KEY=
EOF
  green "  Wrote .env with chosen ports"
else
  yellow "  .env already exists — left untouched"
fi

echo
green "✓ Install complete."
echo
cyan "Next steps:"
echo "  1. Start the server:    ./start.sh"
echo "  2. Open the dashboard:  http://localhost:$HTTP_PORT"
echo "  3. Add an AI key:       http://localhost:$HTTP_PORT/settings"
echo "  4. In Forza:            Data Out → Car Dash → Out IP = your machine, Out Port = $UDP_PORT"
echo
