# Drift Coach — one-shot installer for Windows (PowerShell)
# Run from a PowerShell prompt inside the cloned folder:
#   .\install.ps1
# If PowerShell blocks the script, first run:
#   Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $root

function Write-Cyan($msg)   { Write-Host $msg -ForegroundColor Cyan }
function Write-Green($msg)  { Write-Host $msg -ForegroundColor Green }
function Write-Yellow($msg) { Write-Host $msg -ForegroundColor Yellow }
function Write-Red($msg)    { Write-Host $msg -ForegroundColor Red }

Write-Cyan "[1/5] Checking Node.js >= 20"
try {
  $nodeVer = (node -v).TrimStart('v')
  $major = [int]($nodeVer.Split('.')[0])
  if ($major -lt 20) {
    Write-Red "Node $nodeVer is too old — need 20+"
    Write-Yellow "Install Node 20+ from https://nodejs.org/ and re-run"
    exit 1
  }
  Write-Green "  Node v$nodeVer OK"
} catch {
  Write-Red "Node.js is not installed."
  Write-Yellow "Install Node 20+ from https://nodejs.org/ and re-run"
  exit 1
}

function Test-PortInUse($port) {
  try {
    $listener = New-Object System.Net.Sockets.TcpListener([System.Net.IPAddress]::Any, $port)
    $listener.Start()
    $listener.Stop()
    return $false  # not in use
  } catch {
    return $true   # in use
  }
}

function Test-UdpPortInUse($port) {
  try {
    $listener = New-Object System.Net.Sockets.UdpClient($port)
    $listener.Close()
    return $false
  } catch {
    return $true
  }
}

Write-Cyan "[2/5] Picking an open HTTP port"
$httpPort = if ($env:PORT) { [int]$env:PORT } else { 3002 }
$desiredHttp = $httpPort
for ($i = 0; $i -lt 10; $i++) {
  if (Test-PortInUse $httpPort) { $httpPort++ } else { break }
}
if ($httpPort -ne $desiredHttp) {
  Write-Yellow "  Port $desiredHttp was in use — using $httpPort instead"
}
Write-Green "  HTTP port: $httpPort"

Write-Cyan "[3/5] Picking an open UDP port for Forza Data Out"
$udpPort = if ($env:FORZA_PORT) { [int]$env:FORZA_PORT } else { 5330 }
$desiredUdp = $udpPort
for ($i = 0; $i -lt 5; $i++) {
  if (Test-UdpPortInUse $udpPort) { $udpPort++ } else { break }
}
if ($udpPort -ne $desiredUdp) {
  Write-Yellow "  UDP $desiredUdp was in use — using $udpPort instead"
}
Write-Green "  Forza UDP port: $udpPort  (set this in Forza Data Out > Out Port)"

Write-Cyan "[4/5] Installing dependencies"
if ((Test-Path node_modules) -and (Test-Path package-lock.json)) {
  Write-Green "  node_modules already present; skipping (delete it to force a fresh install)"
} else {
  npm install
}

Write-Cyan "[5/5] Building production bundle"
npm run build

if (-not (Test-Path .env)) {
@"
# Auto-generated by install.ps1. Override anything here.
PORT=$httpPort
HOST=0.0.0.0
FORZA_PORT=$udpPort

# AI provider keys are managed in-app at http://localhost:$httpPort/settings
# Set them there OR uncomment the env vars below.
# OLLAMA_API_KEY=
# ANTHROPIC_API_KEY=
# OPENAI_API_KEY=
"@ | Set-Content .env -Encoding UTF8
  Write-Green "  Wrote .env with chosen ports"
} else {
  Write-Yellow "  .env already exists — left untouched"
}

Write-Host ""
Write-Green "✓ Install complete."
Write-Host ""
Write-Cyan "Next steps:"
Write-Host "  1. Start the server:    .\start.ps1"
Write-Host "  2. Open the dashboard:  http://localhost:$httpPort"
Write-Host "  3. Add an AI key:       http://localhost:$httpPort/settings"
Write-Host "  4. In Forza:            Data Out -> Car Dash -> Out IP = your machine, Out Port = $udpPort"
